final_project/happy_woof/urls.py
from django.contrib import admin
from django.urls import path
from . import settings
from django.contrib.staticfiles.urls import static

import woofy.urls

urlpatterns = [
                  path('admin/', admin.site.urls),
              ] + woofy.urls.urlpatterns

final_project/woofy/urls.py
from django.urls import path, re_path

from happy_woof import settings
from .views import AllPostView, LoginView, LogoutView, UserCreationView, AddNewPostView, AddNewAnnouncementView, \
    ServicePageListView, ServicePageDetailsView, AddServicePageView, PostDetailsView, UserDetailsView, \
    MessageDetailView, PostDeleteView, CommentDeleteView, AnnouncementDeleteView, AnnouncementDetailsView, \
    ServicePageDeleteView, Error404View, EditUserDetailsView, ChangeUserPasswordView, NewMessageView, \
    AllAnnouncementView, EditPostView, EditAnnouncementView, EditCommentView
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', AllPostView.as_view(), name='index'),
    path('all_announcements', AllAnnouncementView.as_view(), name='announcements'),
    path('service_pages/', ServicePageListView.as_view(), name='service-pages'),

    # details
    path('post_details/<int:post_id>/', PostDetailsView.as_view(), name='post-details'),
    path('service_pages/<int:page_id>/', ServicePageDetailsView.as_view(), name='service-page-details'),
    path('msg_details/<int:user_id>/<int:message_id>/', MessageDetailView.as_view(), name='msg-details'),
    path('announcement_details/<int:announcement_id>/', AnnouncementDetailsView.as_view(), name='announcement-details'),

    # add new/send new
    path('add_post/', AddNewPostView.as_view(), name='add-post'),
    path('add_announcement/', AddNewAnnouncementView.as_view(), name='add-announcement'),
    path('add_service_page/', AddServicePageView.as_view(), name='add-service-page'),
    path('add_service_page/', AddServicePageView.as_view(), name='add-service-page'),
    path('new_msg/', NewMessageView.as_view(), name='new-message'),

    # edit
    path('edit_post/<int:post_id>/', EditPostView.as_view(), name='edit-post'),
    path('edit_announcement/<int:announcement_id>/', EditAnnouncementView.as_view(), name='edit-announcement'),
    path('edit_comment/<int:comment_id>/', EditCommentView.as_view(), name='edit-comment'),

    # delete
    path('post_delete/<int:post_id>/', PostDeleteView.as_view(), name='post-delete'),
    path('comment_delete/<int:comment_id>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('announcement_delete/<int:announcement_id>/', AnnouncementDeleteView.as_view(), name='announcement-delete'),
    path('service_page_delete/<int:page_id>/', ServicePageDeleteView.as_view(), name='page-delete'),

    # users
    path('join_in/', UserCreationView.as_view(), name='join-in'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user_details/<int:user_id>/', UserDetailsView.as_view(), name='user-details'),
    path('edit_user/<int:user_id>/', EditUserDetailsView.as_view(), name='edit-user'),
    path('edit_user/password/', ChangeUserPasswordView.as_view(), name='edit-password'),

    # 404
    re_path(r'^[\w\/_-]+$', Error404View.as_view(), name='error')

]
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

final_project/woofy/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class MyUser(AbstractUser):
    email = models.EmailField(unique=True)


class WoofyPost(models.Model):
    content = models.CharField(max_length=250, verbose_name='Treść', help_text='max. 250 znaków')
    # image = models.ImageField(upload_to='post_image', blank=True, null=True)
    city = models.CharField(max_length=64,
                            verbose_name='Miasto',
                            help_text='Podaj swoje miasto, ułatwi to życie innym',
                            default='Cała Polska')
    creation_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)


CATEGORIES = (
    (1, "hodowla"),
    (2, "weterynarz"),
    (3, "psi fryzjer"),
    (4, "sklep zoologiczny"),
    (5, "szkolenie psów"),
    (6, "opieka nad psem"),
    (7, "psi behawiorysta")
)


class ServicePage(models.Model):
    name = models.CharField(max_length=64, verbose_name='Nazwa Twojej firmy')
    category = models.IntegerField(choices=CATEGORIES,
                                   verbose_name='Kategoria',
                                   help_text='Wybierz jedną z kategorii')
    description = models.CharField(max_length=255,
                                   verbose_name='Dodatkowy opis',
                                   help_text='max. 128 znaków',
                                   null=True)
    address = models.CharField(max_length=128, verbose_name='Adres', null=True)
    city = models.CharField(max_length=64, verbose_name='Miasto')
    phone = models.CharField(max_length=16, verbose_name='Telefon', null=True)
    email = models.EmailField(verbose_name='e-mail', null=True)
    homepage = models.URLField(verbose_name='Twoja strona www', null=True)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)


class Announcement(models.Model):
    title = models.CharField(max_length=64, verbose_name='Tytuł ogłoszenia')
    content = models.CharField(max_length=140, verbose_name='Krótki opis',
                               help_text='Opis, który będzie widoczny na stronie głównej')
    all_details = models.TextField(verbose_name='Szczegóły')
    city = models.CharField(max_length=64,
                            verbose_name='Miasto',
                            help_text='Podaj swoje miasto, ułatwi to życie innym',
                            default='Cała Polska')
    creation_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.CharField(max_length=140, verbose_name='Komentarz')
    creation_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    post = models.ForeignKey(WoofyPost, on_delete=models.CASCADE)


class Message(models.Model):
    sender = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='sender', verbose_name='Nadawca')
    receiver = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='receiver', verbose_name='Odbiorca')
    title = models.CharField(max_length=128, verbose_name='Temat')
    content = models.TextField(verbose_name='Wiadomość')
    creation_date = models.DateTimeField(auto_now_add=True)

final_project/woofy/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import Group
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View

from .forms import AddNewPostForm, LoginForm, MyUserForm, AddNewAnnouncementForm, AddServicePageForm, \
    CommentForm, MessageForm, MyUserChangeForm, NewMessageForm, EditPostForm, EditAnnouncementForm, EditCommentForm
from .models import MyUser, WoofyPost, ServicePage, CATEGORIES, Comment, Announcement, Message


class AllPostView(View):
    """
    Main page with the newest posts, announcements
    """

    def get(self, request):
        all_posts = WoofyPost.objects.all().order_by('-creation_date')
        all_comments = Comment.objects.all()
        page = request.GET.get('page', 1)
        paginator = Paginator(all_posts, 5)
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        ctx = {'posts': posts,
               'all_coments': all_comments}
        return render(request, 'woofy/all_posts.html', ctx)


class PostDetailsView(View):
    """
    The view with all details of the post, logged in users can add comments
    """

    def get(self, request, post_id):
        form = CommentForm()
        post = WoofyPost.objects.get(id=post_id)
        comments = Comment.objects.filter(post_id=post_id).order_by('-creation_date')
        user = request.user
        ctx = {'form': form,
               'post': post,
               'comments': comments,
               'user': user}
        return render(request, 'woofy/post_details.html', ctx)

    def post(self, request, post_id):
        form = CommentForm(request.POST)
        post = WoofyPost.objects.get(id=post_id)
        comments = Comment.objects.filter(post_id=post_id).order_by('-creation_date')
        if form.is_valid():
            Comment.objects.create(content=form.cleaned_data['content'], user=request.user, post_id=post.id)
            form = CommentForm()
            ctx = {'form': form, 'post': post, 'comments': comments}
            return render(request, 'woofy/post_details.html', ctx)
        else:
            ctx = {'form': form, 'post': post, 'comments': comments}
            return render(request, 'woofy/post_details.html', ctx)


class EditCommentView(View):
    """
    Comment editing, only for the author of the announcement.
    """

    @method_decorator(login_required)
    def get(self, request, comment_id):
        comment = Comment.objects.get(id=comment_id)
        form = EditCommentForm(initial={'content': comment.content})
        return render(request, 'woofy/edit_announcement.html', {'form': form})

    def post(self, request, comment_id):
        comment = Comment.objects.get(id=comment_id)
        form = EditCommentForm(request.POST)
        if form.is_valid():
            comment.content = form.cleaned_data['content']
            comment.save()
            return redirect('post-details', comment.post_id)
        return render(request, 'woofy/edit_comment.html', {'form': form})


class AddNewPostView(View):
    """
    Adding new post only for logged in users.
    """

    @method_decorator(login_required)
    def get(self, request):
        form = AddNewPostForm()
        return render(request, 'woofy/add_post.html', {'form': form})

    def post(self, request):
        form = AddNewPostForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('index')
        return render(request, 'woofy/add_post.html', {'form': form})


class EditPostView(View):
    """
    Post editing, only for the author of the post.
    """

    @method_decorator(login_required)
    def get(self, request, post_id):
        post = WoofyPost.objects.get(id=post_id)
        form = EditPostForm(initial={'content': post.content, 'city': post.city})
        return render(request, 'woofy/edit_post.html', {'form': form})

    def post(self, request, post_id):
        post = WoofyPost.objects.get(id=post_id)
        form = EditPostForm(request.POST)
        if form.is_valid():
            post.content = form.cleaned_data['content']
            post.city = form.cleaned_data['city']
            post.save()
            return redirect('post-details', post_id)
        return render(request, 'woofy/edit_post.html', {'form': form})


class PostDeleteView(View):
    """
    Confirmation of deleting the post. Only post's author can do this.
    """

    @method_decorator(login_required)
    def get(self, request, post_id):
        return render(request, 'woofy/woofypost_confirm_delete.html')

    def post(self, request, post_id):
        post = WoofyPost.objects.get(id=post_id)
        if request.POST.get('delete') == 'usuń':
            post.delete()
            return redirect('index')
        return redirect('index')


class CommentDeleteView(View):
    """
    Confirmation of deleting the comment. Only comment's author can do this.
    """

    @method_decorator(login_required)
    def get(self, request, comment_id):
        return render(request, 'woofy/comment_confirm_delete.html')

    def post(self, request, comment_id):
        comment = Comment.objects.get(id=comment_id)
        if request.POST.get('delete') == 'usuń':
            comment.delete()
            return redirect('/')
        return redirect('/')


class AllAnnouncementView(View):
    """
    The view with all announcements (only with titles and short descriptions).
    """

    def get(self, request):
        city = request.GET.get('city')
        if city is not None:
            results_announcement = Announcement.objects.filter(city__icontains=city).order_by('-creation_date')
            results_number = len(results_announcement)
        else:
            results_announcement = Announcement.objects.all().order_by('-creation_date')
            results_number = 1
        all_poland_announcement = Announcement.objects.filter(city__icontains='Cała Polska').order_by('-creation_date')
        ctx = {'results_announcement': results_announcement,
               'city': city,
               'results_number': results_number,
               'all_poland_announcement': all_poland_announcement}
        return render(request, 'woofy/all_announcements.html', ctx)


class AnnouncementDetailsView(View):
    """
    The view with long description of the announcement.
    """

    def get(self, request, announcement_id):
        announcement = Announcement.objects.get(id=announcement_id)
        return render(request, 'woofy/announcement_details.html', {'announcement': announcement})


class AddNewAnnouncementView(View):
    """
    Adding new announcement, only for logged in users
    """

    @method_decorator(login_required)
    def get(self, request):
        form = AddNewAnnouncementForm()
        return render(request, 'woofy/add_announcement.html', {'form': form})

    def post(self, request):
        form = AddNewAnnouncementForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('announcements')
        return render(request, 'woofy/add_announcement.html', {'form': form})


class EditAnnouncementView(View):
    """
    Announcement editing, only for the author of the announcement.
    """

    @method_decorator(login_required)
    def get(self, request, announcement_id):
        announcement = Announcement.objects.get(id=announcement_id)
        form = EditAnnouncementForm(initial={'title': announcement.title,
                                             'content': announcement.content,
                                             'all_details': announcement.all_details,
                                             'city': announcement.city})
        return render(request, 'woofy/edit_announcement.html', {'form': form})

    def post(self, request, announcement_id):
        announcement = Announcement.objects.get(id=announcement_id)
        form = EditAnnouncementForm(request.POST)
        if form.is_valid():
            announcement.title = form.cleaned_data['title']
            announcement.content = form.cleaned_data['content']
            announcement.all_details = form.cleaned_data['all_details']
            announcement.city = form.cleaned_data['city']
            announcement.save()
            return redirect('announcement-details', announcement_id)
        return render(request, 'woofy/edit_announcement.html', {'form': form})


class AnnouncementDeleteView(View):
    """
    Confirmation of deleting the announcement. Only announcement's author can do this.
    """

    @method_decorator(login_required)
    def get(self, request, announcement_id):
        announcement = Announcement.objects.get(id=announcement_id)
        return render(request, 'woofy/announcement_confirm_delete.html', {'announcement': announcement})

    def post(self, request, announcement_id):
        announcement = Announcement.objects.get(id=announcement_id)
        if request.POST.get('delete') == 'usuń':
            announcement.delete()
            return redirect('index')
        return redirect('index')


class ServicePageListView(View):
    """
    The view with a list of all service provider's pages.
    """

    def get(self, request):
        service_pages = ServicePage.objects.all().order_by('name')
        categories = dict(CATEGORIES)
        ctx = {'service_pages': service_pages,

final_project/woofy/templates/woofy/add_post.html
{% extends "base/base.html" %}

{% block content %}
<h3>Dodaj nowy post</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <br>
    <input type="submit" class="btn btn-light btn-sm" value="dodaj"> <input type="button" class="btn btn-light btn-sm" value="powrót" onclick="history.back()">
</form>

{% endblock %}

final_project/woofy/templates/woofy/all_announcements.html
{% extends "base/base.html" %}

<!--blok lewy-->
{% block content %}

<h3>Ogłoszenia</h3>

<br>
<p>{% if city is not None %}
        {% if results_number == 0 %}
            Brak wyników wyszukiwania dla "{{ city }}". <br>Sprawdź wyniki dla "Cała Polska":
<!--                        Brak wyników wyszkiwania wyniki dla ogłoszeń na cały kraj -->
                        {% for announcement in all_poland_announcement %}
                        <p>
                            <span class="title">{{announcement.title}}</span><br>
                        {{ announcement.content }}
                        </p>
                        <p class="small-right">
                            <a href="{% url 'user-details' announcement.user.id %}">{{ announcement.user }}</a> {% include 'svg/user.html' %}<br>
                            {{ announcement.creation_date }} {% include 'svg/date.html' %}<br>
                            <span class="city">{{ announcement.city }}</span> {% include 'svg/city.html' %}<br>
                            <a href="{% url 'announcement-details' announcement.id %}">Sprawdź szczegóły</a> {% include 'svg/details.html' %}<br>
                            {% if user == announcement.user %}
                            <a href="{% url 'announcement-delete' announcement.id %}">usuń</a>/<a href="{% url 'edit-announcement' announcement.id %}">edytuj</a>
                            {% else %}
                            {% endif %}
                        </p>
                        <p>{% if user.is_authenticated %}
                            <a href="{% url 'new-message' %}">wyślij wiadomość</a>
                            {% endif %}
                        </p>
                        <hr>
                        {% endfor %}
        {% else %}
            Wyniki wyszukiwania dla "{{ city }}":
<!--            Pokaże wyniki dla wyszukiwania po mieście -->
        {% endif %}
   {% else %}
   {% endif %}
</p>

<!--                Pokaże wszystkie ogłoszenia lub wyniki wyszukwania (jeśli jest wynik)-->
{% for announcement in results_announcement %}
            <p>
                <span class="title">{{announcement.title}}</span><br>
            {{ announcement.content }}
            </p>
            <p class="small-right">
                <a href="{% url 'user-details' announcement.user.id %}">{{ announcement.user }}</a> {% include 'svg/user.html' %}<br>
                {{ announcement.creation_date }} {% include 'svg/date.html' %}<br>
                <span class="city">{{ announcement.city }}</span> {% include 'svg/city.html' %}<br>
                <a href="{% url 'announcement-details' announcement.id %}">Sprawdź szczegóły</a> {% include 'svg/details.html' %}<br>
                {% if user == announcement.user %}
                <a href="{% url 'announcement-delete' announcement.id %}">usuń</a>/<a href="{% url 'edit-announcement' announcement.id %}">edytuj</a>
                {% else %}
                {% endif %}
            </p>
            <p>{% if user.is_authenticated %}
                <a href="{% url 'new-message' %}">wyślij wiadomość</a>
                {% endif %}
            </p>
            <hr>
            {% endfor %}

{% endblock %}

<!-- blok prawy -->
{% block right %}
<a href="{% url 'add-announcement' %}">{% include 'svg/activity.html' %} Dodaj swoje ogłoszenie</a>
<br>
{% include 'svg/details.html' %} W naszej bazie mamy {{ all_announcements|length }} ogłoszeń
<br><br>
<p>{% include 'svg/city.html' %} Szukaj ogłoszeń w Twoim mieście
    <form action="/all_announcements" method="get">
        <input type="text" name="city"> <input type="submit" value="Szukaj">
    </form>
</p>
<p>{% if city is not None %}
        <a href="{% url 'announcements' %}">Pokaż wszystkie ogoszenia</a>
    {% endif %}
</p>
{% endblock %}

final_project/woofy/templates/woofy/all_posts.html
{% extends "base/base.html" %}

<!--blok lewy-->
{% block content %}

<h3>Tablica</h3>

{% include 'base/posts_paginator.html' %}

<br>

{% for post in posts %}
<p>
    <span>{{ post.content }}</span>
</p>
<p class="small-right">
    <!--    user info -->
    <a href="{% url 'user-details' post.user.id %}">{{ post.user }}</a> {% include 'svg/user.html' %}<br>
    <!--    date info -->
    {{ post.creation_date }} {% include 'svg/date.html' %}<br>
    <!--    city info -->
    <span class="city">{{ post.city }}</span> {% include 'svg/city.html' %}<br>
    <!--    delete/edit options -->
    {% if request.user == post.user %}
    <a href="{% url 'post-delete' post.id %}">usuń</a>/<a href="{% url 'edit-post' post.id %}">edytuj</a>
    {% else %}
    {% endif %}<br>
    <!--    comments options -->
    <a href="{% url 'post-details' post.id %}">dodaj komentarz {% include 'svg/comment.html' %}</a>
</p>
<hr>
{% endfor %}

{% include 'base/posts_paginator.html' %}

<p  class="small-center">
    <span><a href="{% url 'add-post' %}">dodaj post</a></span> |
    <span><a href="{% url 'add-announcement' %}">dodaj ogłoszenie</a></span> |
    <span><a href="{% url 'service-pages' %}">usługodawcy</a></span>
</p>

{% endblock %}

final_project/woofy/templates/woofy/announcement_confirm_delete.html
{% extends "base/base.html" %}

{% block content %}
<form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    Czy na pewno chcesz usunąć ogłoszenie <span class="bold">"{{ announcement.title }}"</span>?<br>
    <input type="submit" name="delete" value="usuń" class="btn btn-light btn-sm">
    <input type="button" value="powrót" class="btn btn-light btn-sm" onclick="history.back()">
    <br>
</form>
{% endblock %}

final_project/woofy/templates/woofy/announcement_details.html
{% extends "base/base.html" %}

<!--blok lewy-->
{% block content %}
<h3>{{ announcement.title }}</h3>
<p>{{ announcement.all_details }}</p>
<p class="small-right">{% if user.is_authenticated %}
    <a href="{% url 'new-message' %}">wyślij wiadomość</a> |
	{% endif %}
    <a href="#" onclick="history.back()">powrót</a>
</p>

{% endblock %}


<!-- blok prawy -->
{% block right %}
{% include 'svg/user.html' %} {{ announcement.user }}
<br>
{% include 'svg/date.html' %} {{ announcement.creation_date }}
<br>
{% include 'svg/city.html' %} <span class="city">{{ announcement.city }}</span>
<br>
{% if user == announcement.user %}
<span class="small">
    <a href="{% url 'announcement-delete' announcement.id %}">usuń</a>/<a href="{% url 'edit-announcement' announcement.id %}">edytuj</a>
</span>
{% else %}
{% endif %}

{% endblock %}

final_project/woofy/templates/woofy/comment_confirm_delete.html
{% extends "base/base.html" %}

{% block content %}
<form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    Czy na pewno chcesz usunąć ten komentarz?<br>
    <input type="submit" name="delete" value="usuń" class="btn btn-light btn-sm">
    <input type="button" value="powrót" class="btn btn-light btn-sm" onclick="history.back()">
    <br>
</form>
{% endblock %}

final_project/woofy/templates/woofy/edit_post.html
{% extends "base/base.html" %}

{% block content %}
<h3>Edytuj swój post</h3>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <br>
    <input type="submit" class="btn btn-light btn-sm" value="edytuj"> <input type="button" class="btn btn-light btn-sm" value="powrót" onclick="history.back()">
</form>

{% endblock %}

final_project/woofy/templates/woofy/edit_user.html
{% extends "base/base.html" %}

{% block content %}

<form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    <br>
    <input type="submit" class="btn btn-light btn-sm" value="edytuj"> <input type="button" class="btn btn-light btn-sm" value="powrót" onclick="history.back()">
</form>

{% endblock %}

{% block right %}
    <h3>Dane użytkownika {% include 'svg/user.html' %}</h3>
    <p>login: {{user.username }}</p>

    {% if request.user == user %}
        <p>imię: {{user.first_name }}</p>
        <p>nazwisko: {{ user.last_name }}</p>
        <p>e-mail: {{ user.email }}</p>
    {% endif %}

    <p>z nami od: {{ user.date_joined }}</p>
    {% if request.user == user %}
        <p>rodzaj konta: {{ group }}</p>
    {% endif %}

{% endblock %}

final_project/woofy/templates/woofy/error404.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Coś poszło nie tak...</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Pacifico|Quicksand&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/error.css' %}">

</head>
<body>
<div>
    <span id="error">oops 404</span>
    <h3 id="error-msg">Coś poszło nie tak...<br>Ale nie martw się!<br>Po prostu wrócić na stronę główną.<br>
    <button class="btn btn-light btn-sm" onclick="window.location.href='/';">tutaj &#9825;</button></h3>
</div>
<div id="freepik"><a href="http://www.freepik.com">Designed by Freepik</a></div>



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

final_project/woofy/templates/woofy/service_pages_list.html
{% extends "base/base.html" %}

<!--blok lewy-->
{% block content %}
{% load get_item %}
<h3>Usługi dla Twojego pieska</h3><br>

{% if perms.woofy.add_servicepage %}
<li class="menu">
            <a href="{%url 'add-service-page' %}">dodaj stronę usługi</a>
</li>
{% endif %}

<br><br>
{% for page in service_pages %}
<p>
    {{ page.name }} ({{ categories|get_item:page.category }})
    <br>
    {{ page.address }} <span class="city">{{ page.city }}</span></p>
<p>
    <a href="{% url 'service-page-details' page.id %}">sprawdź szczegóły</a>
    <br>
    <span class="small">
    {% if user == page.user %}
        <a href="{% url 'page-delete' page.id %}">usuń</a>/edytuj
    {% else %}

    {% endif %}</span>
</p>
<hr>
{% endfor %}

{% endblock %}

final_project/woofy/templates/woofy/servicepage_confirm_delete.html
{% extends "base/base.html" %}

{% block content %}
<form method="post" novalidate>
    {% csrf_token %}
    {{ form }}
    Czy na pewno chcesz usunąć informację o usługach?<br>
    <input type="submit" name="delete" value="usuń" class="btn btn-light btn-sm">
    <input type="button" value="powrót" class="btn btn-light btn-sm" onclick="history.back()">
    <br>
</form>
{% endblock %}